/*
 * crcgen.c - generate a 256-entry CRC-16 lookup table as pasteable C source.
 *
 * Build: cc -O2 -std=c99 -Wall -Wextra -o crcgen crcgen.c
 *
 * Usage: crcgen [-p poly] [-r|-n] [-i init] [-x xorout] [-t name] [-c]
 *   -p  polynomial, hex or decimal          (default 0xA001)
 *   -r  reflected table: crc = (crc>>1)^poly, poly given in REVERSED form
 *   -n  normal table:    crc = (crc<<1)^poly, poly given in NORMAL form
 *   -i  initial value                       (default 0xFFFF)
 *   -x  final XOR                           (default 0x0000)
 *   -t  identifier for the emitted array    (default crc_tab16)
 *   -c  emit the array as const (default: plain, matching the original)
 *
 * Always prints the check value: CRC of the ASCII string "123456789".
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static uint16_t tab[256];
static int reflected = 1;

/* Reflected: identical arithmetic to init_crc16_tab(), just hoisted here. */
static void build_reflected(uint16_t poly)
{
    for (unsigned i = 0; i < 256; i++) {
        uint16_t crc = 0;
        uint16_t c   = (uint16_t)i;
        for (unsigned j = 0; j < 8; j++) {
            if ((crc ^ c) & 0x0001u) crc = (uint16_t)((crc >> 1) ^ poly);
            else                     crc = (uint16_t)(crc >> 1);
            c = (uint16_t)(c >> 1);
        }
        tab[i] = crc;
    }
}

/* Normal (MSB-first) table, e.g. poly 0x1021 for CCITT-FALSE / XMODEM. */
static void build_normal(uint16_t poly)
{
    for (unsigned i = 0; i < 256; i++) {
        uint16_t crc = (uint16_t)(i << 8);
        for (unsigned j = 0; j < 8; j++) {
            if (crc & 0x8000u) crc = (uint16_t)((crc << 1) ^ poly);
            else               crc = (uint16_t)(crc << 1);
        }
        tab[i] = crc;
    }
}

static uint16_t crc_update(uint16_t crc, uint8_t b)
{
    if (reflected) return (uint16_t)((crc >> 8) ^ tab[(crc ^ b) & 0xFFu]);
    else           return (uint16_t)((crc << 8) ^ tab[((crc >> 8) ^ b) & 0xFFu]);
}

int main(int argc, char **argv)
{
    unsigned long poly = 0xA001, init = 0xFFFF, xorout = 0x0000;
    const char *name = "crc_tab16";
    int use_const = 0;

    for (int a = 1; a < argc; a++) {
        if      (!strcmp(argv[a], "-r")) reflected = 1;
        else if (!strcmp(argv[a], "-n")) reflected = 0;
        else if (!strcmp(argv[a], "-c")) use_const = 1;
        else if (a + 1 >= argc) { fprintf(stderr, "missing arg for %s\n", argv[a]); return 1; }
        else if (!strcmp(argv[a], "-p")) poly   = strtoul(argv[++a], NULL, 0);
        else if (!strcmp(argv[a], "-i")) init   = strtoul(argv[++a], NULL, 0);
        else if (!strcmp(argv[a], "-x")) xorout = strtoul(argv[++a], NULL, 0);
        else if (!strcmp(argv[a], "-t")) name   = argv[++a];
        else { fprintf(stderr, "unknown option %s\n", argv[a]); return 1; }
    }

    if (reflected) build_reflected((uint16_t)poly);
    else           build_normal((uint16_t)poly);

    /* check value over "123456789" */
    static const uint8_t v[] = "123456789";
    uint16_t crc = (uint16_t)init;
    for (unsigned i = 0; i < 9; i++) crc = crc_update(crc, v[i]);
    crc ^= (uint16_t)xorout;

    printf("/* CRC-16 lookup table -- generated by crcgen\n"
           " * poly=0x%04lX (%s)  init=0x%04lX  xorout=0x%04lX\n"
           " * check(\"123456789\") = 0x%04X\n"
           " */\n",
           poly & 0xFFFF, reflected ? "reflected" : "normal",
           init & 0xFFFF, xorout & 0xFFFF, crc);

    printf("%suint16_t %s[256] = {\n", use_const ? "static const " : "", name);
    for (unsigned i = 0; i < 256; i++) {
        if (i % 8 == 0) printf("    ");
        printf("0x%04X%s", tab[i], (i == 255) ? "" : ",");
        if (i % 8 == 7) printf("\n");
        else            printf(" ");
    }
    printf("};\n");

    fprintf(stderr, "check(\"123456789\") = 0x%04X\n", crc);
    return 0;
}